# Generated by Django 5.0.3 on 2024-04-09 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_corporation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('grant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('grant_name', models.CharField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('corp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('app_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=200)),
                ('status_changed', models.DateTimeField(blank=True, null=True)),
                ('grant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.grant')),
                ('nfp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nfp')),
            ],
        ),
    ]
