# Generated by Django 5.0.3 on 2024-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_email_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfp',
            name='items',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
