# Generated by Django 5.0.4 on 2024-04-14 22:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('app_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(max_length=1000, null=True)),
                ('current_status', models.CharField(choices=[('Pending', 'PENDING'), ('Accepted', 'ACCEPTED'), ('Rejected', 'REJECTED')], default='Pending', max_length=200)),
                ('status_changed', models.DateTimeField(blank=True, null=True)),
                ('grant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.grant')),
                ('nfp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nfp')),
            ],
        ),
    ]
