# Generated by Django 5.0.3 on 2024-04-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_nfp_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nfp',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
