# Generated by Django 5.0.3 on 2024-04-08 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('app_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=200)),
                ('status_changed', models.DateTimeField(null=True)),
                ('grant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.grant')),
                ('nfp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nfp')),
            ],
        ),
    ]
