# Generated by Django 5.0.4 on 2024-04-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_grantapplication'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
