# Generated by Django 5.0.3 on 2024-04-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_grantapplication_status_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='status_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
