# Generated by Django 5.0.4 on 2024-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_grantapplication_nfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='grant_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='status_changed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
