# Generated by Django 4.2.11 on 2024-04-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_corporation_address_alter_corporation_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
