# Generated by Django 5.0.4 on 2024-04-17 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_grant_grant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='corp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
