# Generated by Django 5.0.4 on 2024-04-22 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_grant_corp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('nfp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfp_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indiv_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
