# Generated by Django 5.0.4 on 2024-04-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='nfp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfp_user', to='main.nfp'),
        ),
    ]
