# Generated by Django 5.0.4 on 2024-04-22 18:38

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_donation_nfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[40, 40], upload_to=''),
        ),
    ]
